### PR TITLE
fix BASH_SOURCE checking

### PR DESCRIPTION
**Pull request by anthonyheckmann**
enable sourcing of functions

### CODE REVIEW

**Comment by aristocratos** [comment]
Did you even run the script after making this change?

`-ge` = greater than or equal
`${#BASH_SOURCE[@]}` = 1 : when run directly

This tries to return when not sourced, which creates an error since it can't return when not sourced.

**Comment by anthonyheckmann** [comment]
@aristocratos when I source this with `GNU bash, version 5.0.17(1)-release (x86_64-apple-darwin19.4.0)`, it launches the program. Maybe they changed the BASH_SOURCE variable?

**Comment by aristocratos** [comment]
Are you running `source bashtop` from a shell?
The check is there to be able to run testing scripts which source the file. Sourcing directly from a shell will not work however.
But if you wanna play around with the functions you need to do so from a parent script.

**Comment by anthonyheckmann** [comment]
OK good to know. Actually this is coming up b/c I'm working on a Formula
for homebrew and one of the few tests available is sourcing and checking
that function are loaded.

**Comment by aristocratos** [comment]
Ah, ok. Great to hear. Was hoping somebody would take it upon them self to create a formula :)
Let me know if run into any problems.

**Comment by anthonyheckmann** [comment]
> Ah, ok. Great to hear. Was hoping somebody would take it upon them self to create a formula :)
> Let me know if run into any problems.

Any tests you would recommend post-install? Have been trying something similar to:

    assert_match "function", 'bash -c  "source #{bin}/bashtop && type -t main_loop"'.

However getting it to source correctly has been a challenge.

**Comment by aristocratos** [comment]
Got bats testing setup in #130 but haven't written any proper tests yet. 

But checking for main_loop() sounds like a good start, could always be expanded later. But you would need to have a external test. Something like:

external_test.sh:
```bash
source bashtop
echo "$(type -t main_loop)"
```

And then:
```ruby
assert_match "function", shell_output("bash external_test.sh").strip
```

Could possibly work?

**Comment by aristocratos** [comment]
On second thought, you wouldn't need the echo... remembered this isn't python...
```bash
source bashtop
type -t main_loop
```

**Comment by aristocratos** [comment]
You could even just have a bash wrapper file and pass any tests as arguments:
test_wrapper.sh:
```bash
source bashtop
$*
```
```ruby
assert_match "function", shell_output("bash test_wrapper.sh type -t main_loop").strip
```

**Comment by anthonyheckmann** [comment]
> You could even just have a bash wrapper file and pass any tests as arguments:
> test_wrapper.sh:
> 
> ```shell
> source bashtop
> $*
> ```
> 
> ```ruby
> assert_match "function", shell_output("bash test_wrapper.sh type -t main_loop").strip
> ```

After trial and error, I ended up with this fun nugget:
```ruby
test do
    loader=<<~EOS
      #!/usr/bin/env bash
      source "#{bin}/bashtop"
      type -t main_loop    
    EOS
assert_match "function", shell_output("echo '#{loader}' > tmp.sh && chmod +x tmp.sh && ./tmp.sh ")

I tried but could't get the here doc to pipe directly to bash and still source correctly.

**Comment by aristocratos** [comment]
Yeah, need to be sourced from an actual file since ${BASH_SOURCE} array appends the filename of parent(s) and sourced file.
You could shorten a little bit by losing the shebang in the heredoc and starting the script with bash directly:
```ruby
assert_match "function", shell_output("echo '#{loader}' > tmp.sh && bash ./tmp.sh ")
```

**Pull request closed without merging**
