### PR TITLE
[Syntax] Remove useless curly brackets around expansions

### PR DESCRIPTION
**Pull request by Camusensei**

### CODE REVIEW

**Comment by Camusensei** [comment]
You'll have to help me out here, that makes two declined pull requests, and I don't know why ;)
I haven't found a contributing guide so I don't really know what you expect from contributors.
Both pull requests were for homogeneity but for this one maybe you want me to add the curly brackets everywhere they are not?

**Comment by aristocratos** [comment]
I've primarily been using the unnecessary curly brackets and quotes for better syntax highlighting in vscode. And since you didn't give a reason why a syntax design choice should be changed I closed them.

It's a lot of shell script, so extra highlighting helps :)

I'm gonna fix up some contributing guidelines tomorrow when I've got some free time.

**Comment by Camusensei** [comment]
I understand, so are you alright with another pull request where I add curly brackets everywhere for consistency? Or would that be refused as well?

**Comment by aristocratos** [comment]
No that would definitely be welcome :)

Not gonna have time to look through anything right now though, gotta get some sleep.

**Comment by Camusensei** [comment]
Great, and don't worry even if it remains open for days, I won't mind ;)

**Comment by aristocratos** [comment]
I noticed looking through the code that I mostly used curly brackets in denser chunks of code for better visibility. So on second thought I don't think it would be necessary to convert all of them. At least no functional reason to do so.

**Pull request closed without merging**
