### PR TITLE
some refactoring

### PR DESCRIPTION
**Pull request by ukH9YFxczKfxEnNECPyq**
hope it some of it will be usefull

### CODE REVIEW

**Comment by aristocratos** [comment]
The tab spacing looks fine in vscode. Did you follow the style guide at the beginning of the file?
```bash
# indent type=tab
# tab size=4
```
About the IF statements, it's just my preferred way of writing bash since I think it gives better readability.

**Comment by ukH9YFxczKfxEnNECPyq** [comment]
it seems I've missed this moment. well, will close request
could i ask what is the meaning of #? and #* in this program?

**Comment by aristocratos** [comment]
Its for extension "Better Comments" in vscode, gives color coding on comments which can be really useful to distinguish between descriptions, notes and the like.

**Comment by aristocratos** [comment]
If you use vscode and write a lot of bash, I would also recommend "Bash IDE" which provides symbols for variables and functions to for example show all functions in the sidebar. And the "shellcheck" extension. Makes writing and keeping track of bash a breeze.

**Pull request closed without merging**
